name: Build Redmi Note 9 Pro Kernel (Lineage-19.1)

on:
  workflow_dispatch:

permissions:
  contents: write # 赋予自动发布 Release 固件包的权限

jobs:
  build-kernel:
    name: Build Kernel for Gauguin
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_xiaomi_gauguin
          ref: lineage-19.1
          path: kernel-source
          depth: 1

      - name: Patch Kernel Makefile
        run: |
          cd kernel-source
          # 1. 删掉导致 Clang 报错的断言
          sed -i '/Clang with Android --target detected. Did you specify CLANG_TRIPLE?/d' Makefile
          # 2. 将过旧内核需要的链接器硬编码进 Makefile
          sed -i 's/^ARCH\s\??=/LD := ld.lld\nARCH ?=/' Makefile

      - name: Build Android Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          # 1. 指定本地已打好补丁的内核源码路径
          kernel-url: ./kernel-source/
          config: vendor/gauguin_user_defconfig
          arch: arm64
          
          # 2. 编译工具链设置 (完美匹配您原本的配置)
          aosp-clang: true
          aosp-gcc: true
          android-version: 12
          aosp-clang-version: r383902
          
          # 3. 核心功能支持 (完整补回原配置要求)
          ksu: true
          ksu-version: v0.9.5
          lxc: true
          lxc-patch: false
          
          # 4. 打包与自动发布
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
