name: Build Redmi Note 9 Pro Kernel (Lineage-18.1)

on:
  workflow_dispatch:

permissions:
  contents: write # 赋予自动发布 Release 固件包的权限

jobs:
  build-kernel:
    name: Build Kernel for Gauguin Lineage-18.1
    runs-on: ubuntu-latest
     # 关键：指定在第三方维护的 ubuntu:20.04 编译专用容器内执行
    container:
      # 该镜像内置了 AOSP/LineageOS 所需的所有旧版依赖和工具链环境
      image: lineageos4microg/docker-lineage-cicd:lineage-19.0
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_xiaomi_gauguin
          ref: lineage-18.1
          path: kernel-source

      - name: Build Android Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          # 1. 指定本地已打好补丁的内核源码路径
          kernel-url: ./kernel-source/
          config: vendor/gauguin_user_defconfig
          arch: arm64
          
          # 2. 编译工具链设置
          aosp-clang: true
          aosp-gcc: true
          android-version: 11
          aosp-clang-version: r383902
          
          # 3. 核心功能支持
          ksu: true
          ksu-version: v0.9.5
          lxc: true
          lxc-patch: false
          
          # 4. 打包与自动发布
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
